### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by CharleO** [HBM/saleae-hla-io-link#1] opened 2021-10-28 20:05 UTC
Logic 2 Version 2.3.39
A error occurs after few start and stop.
IO Link error - AttributeError("'NoneType' object has no attribute 'append'")
  File "IOLinkAnalyzer.py", line 138, in decode
    `ret = self.process.send(frame)`

  File "IOLinkAnalyzer.py", line 128, in parseByte
    `ret = pendingFrame.append((yield None))`

**Comment by sherber** [comment] 2022-01-17 13:32
Hi CharleO,

sorry for the late reply. 
Unfortunately, the analyzer can currently not determine on its own at which byte an IO-Link frame ends and the next one starts. The timing makes it obvious when looking at it, but it's a bit cumbersome to implement.

At the start of your capture, you probably captured the fragment of an IO-Link frame. Try deleting these first bytes, and it should be working as intended.

**Comment by sherber** [comment] 2022-02-28 09:39
Hi CharleO,

I have fixed the issue in release v1.1.0. Unfortunately it has not yet trickled down through the marketplace. Until it does you can  clone the repository directly to your local machine and click "Load Existing Extension" in the Logic2 software to import the analyzer.
I'll close the issue as fixed. Feel free to open additional issues if you are still encountering problems.

**Closed as completed by sherber** 2022-02-28 09:39 UTC
